import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { ToastContainer } from "react-toastify";


import LoginModalWrapper from "../components/LoginModalWrapper";
import { AuthProvider } from "@/context/AuthContex";
import { Providers } from "./Provider";
import UserLoader from "./load/UserLoader";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chef's World",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon-v2.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <AuthProvider>
          {/* Navbar */}
          <Providers>
            <Navbar />
             <UserLoader />
 <Toaster position="top-center" />
            {/* Content */}
            <main className="flex-1">
              <div className="mx-auto p-1 sm:px-0 sm:max-w-xl md:max-w-2xl lg:max-w-3xl xl:max-w-7xl">
                {children}
              </div>
            </main>
            <Footer />
            <LoginModalWrapper />
          </Providers>

          {/* Footer */}

          <ToastContainer position="bottom-right" />
        </AuthProvider>
      </body>
    </html>
  );
}
